FROM ubuntu:16.04
LABEL updated_on="2019-10-18 09:00"
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python3 python3-setuptools python3-pip gunicorn3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
COPY lab-4-app /flaskapp
WORKDIR /flaskapp
RUN pip3 install -r requirements.txt
EXPOSE 5000
ENTRYPOINT "./startup.sh"

FROM nginx:1.13
COPY flaskapp.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

resolver 127.0.0.11 valid=1s;
server {
set $alias "flaskapp";
location / {
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_pass http://$alias:5000;
}
listen 80;
}


version: "2.0"
services:
flaskapp:
build: ./flaskapp
image: user/flaskapp
networks:
- app
nginx:
image: nginx
ports:
- 8080:80
networks:
- app
depends_on:
- flaskapp
networks:
app: